apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-aks-stg
  project: giri
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: giri-aks
  config:
    kind: aksClusterConfig
    metadata:
      name: giri-aks-stg
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile: {}
          dnsPrefix: giri-aks-stg-dns
          kubernetesVersion: 1.25.6
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
        sku:
          name: Basic
          tier: Free
        tags:
          email: giridharaprasad@rafay.co
          env: qa
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 3
          maxPods: 110
          minCount: 3
          mode: System
          orchestratorVersion: 1.25.6
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B2ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: giri
  proxyConfig: {}
  type: aks
status:
  aks:
    nodepools:
    - createdAt: "2023-04-14T03:26:21Z"
      id: jkewd4k
      name: primary
      provisionStatus: NODEGROUP_PROVISION_COMPLETE
  blueprint:
    name: minimal
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: pending
    status: "False"
    type: ClusterNodeSyncSucceeded
  - reason: all tasks/workloads synced
    status: "True"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint handled
    status: "False"
    type: ClusterNamespaceSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-04-14T03:24:37Z"
  displayName: giri-aks-stg
  extra:
    vaultIntegration: {}
  id: kexyjg2
  name: giri-aks-stg
  provisionStatus: OPERATOR_BOOTSTRAP_INPROGRESS
