apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-az-stage
  project: giri
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: giri-azure-cost
  config:
    kind: aksClusterConfig
    metadata:
      name: giri-az-stage
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile: {}
          dnsPrefix: giri-az-stage-dns
          kubernetesVersion: 1.24.9
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          orchestratorVersion: 1.24.9
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B2ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: giri
  proxyConfig: {}
  type: aks
status:
  aks:
    nodepools:
    - createdAt: "2023-03-30T12:09:33Z"
      id: emp9e02
      kubeVersion: 1.24.9
      name: primary
      provisionStatus: NODEGROUP_PROVISION_COMPLETE
  blueprint:
    name: minimal
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: all nodes synced
    status: "True"
    type: ClusterNodeSyncSucceeded
  - reason: all namespaces synced
    status: "True"
    type: ClusterNamespaceSyncSucceeded
  - reason: all tasks/workloads synced
    status: "True"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-03-30T12:08:54Z"
  displayName: giri-az-stage
  extra:
    vaultIntegration: {}
  id: krdqqw2
  name: giri-az-stage
  provisionStatus: CLUSTER_PROVISION_COMPLETE
