apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-mar10-eks
  project: giri
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: giri-aws
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    metadata:
      name: giri-mar10-eks
      region: us-west-2
      tags:
        email: giridharaprasad@rafay.co
        env: qa
      version: "1.24"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 0
      name: ng-35af9978
      version: "1.24"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
status:
  blueprint:
    name: minimal
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: all nodes synced
    status: "True"
    type: ClusterNodeSyncSucceeded
  - reason: all namespaces synced
    status: "True"
    type: ClusterNamespaceSyncSucceeded
  - reason: all tasks/workloads synced
    status: "True"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-03-10T12:12:02Z"
  displayName: giri-mar10-eks
  extra:
    vaultIntegration: {}
  id: 2djqr02
  name: giri-mar10-eks
  provisionStatus: CLUSTER_PROVISION_COMPLETE
