apiVersion: security.k8smgmt.io/v3
kind: NamespaceNetworkPolicy
metadata:
  name: system-ns-policy
  project: giri-cost
spec:
  rules:
  - name: system-ns-rule1
    version: system-ns-rule-version1
  version: system-policy-v1
