apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-conf
  project: giri-cost
spec:
  base:
    name: default
    version: 1.19.0
  costProfile:
    enabled: true
    name: default-cost-profile-azure
    version: version-1666369365
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        enabled: true
      prometheusAdapter:
        enabled: true
  type: custom
  version: test4
