apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    control-plane: "true"
    kubernetes.io/metadata.name: calico-system
    name: calico-system
  name: calico-system
  project: giri
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-aks-demo
