apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: patch-ns
  project: giri
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-aks-patch
  resourceQuotas: {}
