apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: rabbitmq
  project: giri
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-aks-demo
  resourceQuotas: {}
