apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: madhueks-stage-stability
  project: madhuproject
spec:
  blueprintConfig:
    name: bp-addon-cluster-override
    version: last-v2
  cloudCredentials: madhuaws117x
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    metadata:
      name: madhueks-stage-stability
      region: us-west-2
      tags:
        email: madhu@rafay.co
        env: qa
      version: "1.23"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.xlarge
      maxSize: 3
      minSize: 0
      name: ng1
      version: "1.23"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
status:
  blueprint:
    name: bp-addon-cluster-override
    version: last-v2
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: all nodes synced
    status: "True"
    type: ClusterNodeSyncSucceeded
  - reason: blueprint placement processed
    status: "False"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint handled
    status: "False"
    type: ClusterNamespaceSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-03-03T12:08:23Z"
  displayName: madhueks-stage-stability
  extra:
    vaultIntegration: {}
  id: kyoqzdm
  name: madhueks-stage-stability
  provisionStatus: CLUSTER_PROVISION_COMPLETE
