apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: madhuaks-stage1
  project: madhuproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: test-azure-provisioning
  config:
    kind: aksClusterConfig
    metadata:
      name: madhuaks-stage1
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile: {}
          dnsPrefix: madhuaks-stage1-dns
          kubernetesVersion: 1.24.9
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 40
          minCount: 1
          mode: System
          orchestratorVersion: 1.24.9
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: madhurgroup
  proxyConfig: {}
  type: aks
status:
  aks:
    nodepools:
    - createdAt: "2023-03-29T12:59:17Z"
      id: 1kyzdg2
      kubeVersion: 1.24.9
      name: primary
      provisionStatus: NODEGROUP_PROVISION_COMPLETE
  blueprint:
    name: default
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: all nodes synced
    status: "True"
    type: ClusterNodeSyncSucceeded
  - reason: blueprint placement processed
    status: "False"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint handled
    status: "False"
    type: ClusterNamespaceSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-03-29T12:58:36Z"
  displayName: madhuaks-stage1
  extra:
    vaultIntegration: {}
  id: kgj4njk
  name: madhuaks-stage1
  provisionStatus: CLUSTER_PROVISION_COMPLETE
