apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: madhueks-stage-stability
  project: madhuproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: madhuaws117x
  config:
    metadata:
      name: madhueks-stage-stability
      region: us-west-2
      tags:
        email: madhu@rafay.co
        env: qa
      version: "1.23"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 2
      name: ng1
      version: "1.23"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
status:
  blueprint:
    name: minimal
  conditions:
  - reason: registered
    status: "True"
    type: ClusterRegisterSucceeded
  - reason: checked in
    status: "True"
    type: ClusterCheckInSucceeded
  - reason: pending
    status: "False"
    type: ClusterNodeSyncSucceeded
  - reason: all namespaces synced
    status: "True"
    type: ClusterNamespaceSyncSucceeded
  - reason: all tasks/workloads synced
    status: "True"
    type: ClusterBlueprintSyncSucceeded
  - reason: blueprint synced
    status: "True"
    type: ClusterReady
  createdAt: "2023-03-03T12:08:23Z"
  displayName: madhueks-stage-stability
  extra:
    vaultIntegration: {}
  id: kyoqzdm
  name: madhueks-stage-stability
  provisionStatus: BOOTSTRAP_DELETION_INPROGRESS
