apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: madhuaks-stage-1
  project: madhuproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: test-azure-provisioning
  config:
    kind: aksClusterConfig
    metadata:
      name: madhuaks-stage-1
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile: {}
          dnsPrefix: madhuaks-stage-1-dns
          kubernetesVersion: 1.25.6
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.25.6
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: madhurgroup
  proxyConfig: {}
  type: aks
status:
  aks:
    nodepools:
    - createdAt: "2023-04-13T13:14:06Z"
      id: 3mxp7ok
      name: primary
  blueprint:
    name: minimal
  conditions:
  - reason: pending
    status: "False"
    type: ClusterRegisterSucceeded
  - reason: pending
    status: "False"
    type: ClusterCheckInSucceeded
  - reason: pending
    status: "False"
    type: ClusterNodeSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterBlueprintSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterNamespaceSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterReady
  createdAt: "2023-04-13T13:12:37Z"
  displayName: madhuaks-stage-1
  extra:
    vaultIntegration: {}
  id: 2l8gvnk
  name: madhuaks-stage-1
  provisionStatus: INFRA_CREATION_INPROGRESS
