apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test
  project: giri
spec:
  base:
    name: default
    version: 1.16.0
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableIngress: true
    enableLogging: false
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  networkPolicy: {}
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: "n"
