apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns1
  project: giri
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  networkPolicyParams:
    networkPolicyEnabled: true
    policies:
    - name: pol1
      version: v11
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-np1
  resourceQuotas: {}
