apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: demo2
  project: madhuproject
spec:
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: cluster
      value: demo
  resourceQuotas: {}
