apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: gpu-operator-resources
  project: madhuproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: test-mks-1
  resourceQuotas: {}
