apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: madhutest1
  project: madhuproject
spec:
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: madhu-eks123
  resourceQuotas: {}
