apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: madhuns5
  project: madhuproject
spec:
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: madhufinal
  resourceQuotas: {}
