apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: madhuco
  project: madhuproject
spec:
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: madhueks-new1
    - key: rafay.dev/clusterName
      value: madhu-calico-retest2
  resourceQuotas: {}
